# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cab2a62116369999a1c5316e9655e283863aab1a2fcaba96734bb42476f81116f3c09e96d3210bd1fc85d1c8522ba2738787992c5d8763f3b4efffc0738e2612

test:
  secret_key_base: 5e9f6ed11f8a05ea91872c490ec8719461652bf7d8d7f9628111aeede71234fa8ef5e4092f06d5c0f543afea3b8dbc30c8783b7e620a33071c546abb4c2aa557

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
